# Generated by Django 6.0.4 on 2026-04-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseprogress',
            name='stage1_video_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserVocabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2')])),
                ('confidence', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vocabitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'vocab_item', 'stage'), name='unique_user_vocab_stage')],
            },
        ),
    ]
