# Generated by Django 6.0.4 on 2026-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userexerciseprogress_stage1_video_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabitem',
            options={},
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='mora',
            field=models.JSONField(blank=True, default=list, help_text="List of mora, stored as JSON (e.g. ['か', 'え', 'る'])."),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='pitch_end',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-based index where HIGH ends (inclusive). Can equal start.', null=True),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='pitch_start',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-based index where HIGH starts (inclusive).', null=True),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='reading_hira',
            field=models.CharField(blank=True, help_text='Hiragana reading used for Stage 2 typing + pitch UI (e.g. かえる).', max_length=100),
        ),
    ]
