# Generated by Django 6.0.4 on 2026-06-29 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vocabitem_options_vocabitem_mora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenceitem',
            name='jp_segments',
            field=models.JSONField(blank=True, default=list, help_text="Japanese sentence segments, e.g. ['わたしは', 'バナナを', '食べます']"),
        ),
        migrations.CreateModel(
            name='UserSentenceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sentenceitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'sentence_item'), name='unique_user_sentence_progress')],
            },
        ),
    ]
