# Generated by Django 6.0.4 on 2026-07-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sentenceitem_jp_segments_usersentenceprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabitem',
            name='romaji',
            field=models.CharField(blank=True, help_text='Optional romaji answer accepted in Stage 2, e.g. eigo, hadashi, mugendai.', max_length=100),
        ),
    ]
