# Generated by Django 6.0.4 on 2026-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vocabitem_romaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenceitem',
            name='jp_kana',
            field=models.TextField(blank=True, help_text='Kana-only version of the Japanese sentence, e.g. わたしは にほんに きました。'),
        ),
        migrations.AddField(
            model_name='sentenceitem',
            name='jp_kana_segments',
            field=models.JSONField(blank=True, default=list, help_text="Kana-only sentence segments, e.g. ['わたしは', 'にほんに', 'きました']"),
        ),
        migrations.AlterField(
            model_name='sentenceitem',
            name='jp_segments',
            field=models.JSONField(blank=True, default=list, help_text="Japanese sentence segments, e.g. ['私は', '日本に', '来ました']"),
        ),
    ]
